// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// localStorage can be null/blocked in Safari private mode or sandboxed iframes
const safeStorage = (() => {
  try { return window.localStorage; } catch { return undefined; }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    ...(safeStorage && { storage: safeStorage }),
    persistSession: true,
    autoRefreshToken: true,
  }
});